https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/index.json 

# https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/index.csv

In [1]:
import pandas as pd

In [2]:
# ! wget https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/index.csv

In [3]:
! head index.csv

"FormatVersion","v1.0"
"Disclaimer","This pricing list is for informational purposes only. All prices are subject to the additional terms included in the pricing pages on http://aws.amazon.com. All Free Tier prices are also subject to the terms included at https://aws.amazon.com/free/"
"Publication Date","2020-12-29T06:55:13Z"
"Version","20201229065513"
"OfferCode","AmazonEC2"
"SKU","OfferTermCode","RateCode","TermType","PriceDescription","EffectiveDate","StartingRange","EndingRange","Unit","PricePerUnit","Currency","RelatedTo","LeaseContractLength","PurchaseOption","OfferingClass","Product Family","serviceCode","Location","Location Type","Instance Type","Current Generation","Instance Family","vCPU","Physical Processor","Clock Speed","Memory","Storage","Network Performance","Processor Architecture","Storage Media","Volume Type","Max Volume Size","Max IOPS/volume","Max IOPS Burst Performance","Max throughput/volume","Provisioned","Tenancy","EBS Optimized","Operating System","License Model","Group","Group Description","Transfer Type","From Location","From Location Type","To Location","To Location Type","usageType","operation","CapacityStatus","Dedicated EBS Throughput","ECU","Elastic Graphics Type","Enhanced Networking Supported","GPU","GPU Memory","Instance","Instance Capacity - 10xlarge","Instance Capacity - 12xlarge","Instance Capacity - 16xlarge","Instance Capacity - 18xlarge","Instance Capacity - 24xlarge","Instance Capacity - 2xlarge","Instance Capacity - 32xlarge","Instance Capacity - 4xlarge","Instance Capacity - 8xlarge","Instance Capacity - 9xlarge","Instance Capacity - large","Instance Capacity - medium","Instance Capacity - metal","Instance Capacity - xlarge","instanceSKU","Intel AVX Available","Intel AVX2 Available","Intel Turbo Available","Normalization Size Factor","Physical Cores","Pre Installed S/W","Processor Features","Product Type","Resource Type","serviceName","Volume API Name"
"YQHNG5NBWUE3D67S","4NA7Y494T4","YQHNG5NBWUE3D67S.4NA7Y494T4.6YS6EN2CT7","Reserved","Red Hat Enterprise Linux (Amazon VPC), m4.xlarge reserved instance applied","2017-04-30","0","Inf","Hrs","0.1963000000","USD",,"1yr","No Upfront","standard","Compute Instance","AmazonEC2","US East (Ohio)","AWS Region","m4.xlarge","Yes","General purpose","4","Intel Xeon E5-2676 v3 (Haswell)","2.4 GHz","16 GiB","EBS only","High","64-bit",,,,,,,,"Dedicated",,"RHEL","No License required",,,,,,,,"USE2-DedicatedUsage:m4.xlarge","RunInstances:0010","Used","750 Mbps","13",,"Yes",,,,,,,,,,,,,,,,,,,"Yes","Yes","Yes","8",,"NA","Intel AVX; Intel AVX2; Intel Turbo",,,"Amazon Elastic Compute Cloud",
"38UAGGZF2TPDQSYB","Z2E3P23VKM","38UAGGZF2TPDQSYB.Z2E3P23VKM.6YS6EN2CT7","Reserved","Linux/UNIX (Amazon VPC), t4g.medium reserved instance applied","2020-09-01","0","Inf","Hrs","0.0167000000","USD",,"3yr","No Upfront","convertible","Compute Instance","AmazonEC2","US West (Oregon)","AWS Region","t4g.medium","Yes","General purpose","2","AWS Graviton2 Processor","2.5 GHz","4 GiB","EBS only","Up to 5 Gigabit","64-bit",,,,,,,,"Shared",,"Linux","No License required",,,,,,,,"USW2-BoxUsage:t4g.medium","RunInstances","Used","Up to 2085 Mbps","NA",,"No",,,,,,,,,,,,,,,,,,,"No","No","No","2",,"NA",,,,"Amazon Elastic Compute Cloud",
"FS9HBBMCNT422SDM","38NPMPTW36","FS9HBBMCNT422SDM.38NPMPTW36.6YS6EN2CT7","Reserved","Windows with SQL Server Enterprise (Amazon VPC), r5dn.metal reserved instance applied","2020-04-01","0","Inf","Hrs","22.0310000000","USD",,"3yr","Partial Upfront","standard","Compute Instance (bare metal)","AmazonEC2","AWS GovCloud (US-West)","AWS Region","r5dn.metal","Yes","Memory optimized","96","Intel Xeon Platinum 8259 (Cascade Lake)","3.1 GHz","768 GiB","4 x 900 NVMe SSD","100 Gigabit","64-bit",,,,,,,,"Dedicated",,"Windows","No License required",,,,,,,,"UGW1-DedicatedUsage:r5dn.metal","RunInstances:0102","Used","12000 Mbps","NA",,"No",,,,,,,,,,,,,,,,,,,"No","No","No","192",,"SQL Ent",,,,"Amazon Elastic Compute Cloud",
"AF4M9XS62QDH5P8S","BPH4J8HBKS","AF4M9XS62QDH5P8S.BPH4J8HBKS.6YS6EN2CT7","Reserved","Linux/UNIX (Amazon VPC), i3.xlarge reserved instance applied","2017-04-30","0","Inf","Hrs","0.1950000000","USD",,"3yr","No Upfront","standard","Compute Instance","AmazonEC2","Asia Pacific (Tokyo)","AWS Region","i3.xlarge","Yes","Storage optimized","4","Intel Xeon E5-2686 v4 (Broadwell)","2.3 GHz","30.5 GiB","1 x 950 NVMe SSD","Up to 10 Gigabit","64-bit",,,,,,,,"Dedicated",,"Linux","No License required",,,,,,,,"APN1-DedicatedUsage:i3.xlarge","RunInstances","Used","850 Mbps","16",,"Yes",,,,,,,,,,,,,,,,,,,"Yes","Yes","Yes","8",,"NA","Intel AVX; Intel AVX2; Intel Turbo",,,"Amazon Elastic Compute Cloud",

In [4]:
# clip out the first 5 comment lines with sed

In [5]:
!sed -e '1,5d' < index.csv >pricelist.csv

In [6]:
df = pd.read_csv('pricelist.csv')

/opt/tljh/user/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3147: DtypeWarning: Columns (11,29,30,31,32,33,34,35,37,40,41,42,43,44,45,46,52,55,56,79,80,82) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [7]:
df

,SKU,OfferTermCode,RateCode,TermType,PriceDescription,EffectiveDate,StartingRange,EndingRange,Unit,PricePerUnit,...,Intel AVX2 Available,Intel Turbo Available,Normalization Size Factor,Physical Cores,Pre Installed S/W,Processor Features,Product Type,Resource Type,serviceName,Volume API Name
0,YQHNG5NBWUE3D67S,4NA7Y494T4,YQHNG5NBWUE3D67S.4NA7Y494T4.6YS6EN2CT7,Reserved,"Red Hat Enterprise Linux (Amazon VPC), m4.xlar...",2017-04-30,0.0,inf,Hrs,0.1963,...,Yes,Yes,8.0,NaN,NaN,Intel AVX; Intel AVX2; Intel Turbo,NaN,NaN,Amazon Elastic Compute Cloud,NaN
1,38UAGGZF2TPDQSYB,Z2E3P23VKM,38UAGGZF2TPDQSYB.Z2E3P23VKM.6YS6EN2CT7,Reserved,"Linux/UNIX (Amazon VPC), t4g.medium reserved i...",2020-09-01,0.0,inf,Hrs,0.0167,...,No,No,2.0,NaN,NaN,NaN,NaN,NaN,Amazon Elastic Compute Cloud,NaN
2,FS9HBBMCNT422SDM,38NPMPTW36,FS9HBBMCNT422SDM.38NPMPTW36.6YS6EN2CT7,Reserved,Windows with SQL Server Enterprise (Amazon VPC...,2020-04-01,0.0,inf,Hrs,22.0310,...,No,No,192.0,NaN,SQL Ent,NaN,NaN,NaN,Amazon Elastic Compute Cloud,NaN
3,AF4M9XS62QDH5P8S,BPH4J8HBKS,AF4M9XS62QDH5P8S.BPH4J8HBKS.6YS6EN2CT7,Reserved,"Linux/UNIX (Amazon VPC), i3.xlarge reserved in...",2017-04-30,0.0,inf,Hrs,0.1950,...,Yes,Yes,8.0,NaN,NaN,Intel AVX; Intel AVX2; Intel Turbo,NaN,NaN,Amazon Elastic Compute Cloud,NaN
4,TDQJ4JGM4HQ9852M,R5XV2EPZQZ,TDQJ4JGM4HQ9852M.R5XV2EPZQZ.2TG2D8R56U,Reserved,Upfront Fee,2018-03-31,NaN,NaN,Quantity,6972.0000,...,Yes,Yes,4.0,NaN,SQL Std,Intel AVX; Intel AVX2; Intel Turbo,NaN,NaN,Amazon Elastic Compute Cloud,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1814576,KBKESSYRBJ4586CZ,VJWZNREJX2,KBKESSYRBJ4586CZ.VJWZNREJX2.6YS6EN2CT7,Reserved,"SUSE Linux (Amazon VPC), m4.16xlarge reserved ...",2017-10-31,0.0,inf,Hrs,0.0000,...,Yes,Yes,128.0,NaN,NaN,Intel AVX; Intel AVX2; Intel Turbo,NaN,NaN,Amazon Elastic Compute Cloud,NaN
1814577,3HMFRRC894JPHQUW,JRTCKXETXF,3HMFRRC894JPHQUW.JRTCKXETXF.6YS6EN2CT7,OnDemand,$7.634 per Dedicated Unused Reservation Window...,2020-12-01,0.0,inf,Hrs,7.6340,...,No,No,32.0,NaN,SQL Ent,AVX; AVX2; AMD Turbo,NaN,NaN,Amazon Elastic Compute Cloud,NaN
1814578,JPGAQ53XCWQCUY82,7NE97W5U4E,JPGAQ53XCWQCUY82.7NE97W5U4E.6YS6EN2CT7,Reserved,"Linux with SQL Server Standard (Amazon VPC), m...",2018-05-31,0.0,inf,Hrs,15.4920,...,Yes,Yes,192.0,NaN,SQL Std,Intel AVX; Intel AVX2; Intel AVX512; Intel Turbo,NaN,NaN,Amazon Elastic Compute Cloud,NaN
1814579,FVR474X37D9AKDX2,MZU6U2429S,FVR474X37D9AKDX2.MZU6U2429S.2TG2D8R56U,Reserved,Upfront Fee,2019-03-01,NaN,NaN,Quantity,9437.0000,...,Yes,Yes,8.0,NaN,SQL Web,Intel AVX; Intel AVX2; Intel AVX512; Intel Turbo,NaN,NaN,Amazon Elastic Compute Cloud,NaN
1814580,626GBVVWXVKZXRCJ,7NE97W5U4E,626GBVVWXVKZXRCJ.7NE97W5U4E.6YS6EN2CT7,Reserved,"Linux with SQL Server Enterprise (Amazon VPC),...",2020-04-01,0.0,inf,Hrs,29.1580,...,Yes,Yes,128.0,NaN,SQL Ent,Intel AVX; Intel AVX2; Intel Turbo,NaN,NaN,Amazon Elastic Compute Cloud,NaN

In [8]:
df.columns

Index(['SKU', 'OfferTermCode', 'RateCode', 'TermType', 'PriceDescription',
       'EffectiveDate', 'StartingRange', 'EndingRange', 'Unit', 'PricePerUnit',
       'Currency', 'RelatedTo', 'LeaseContractLength', 'PurchaseOption',
       'OfferingClass', 'Product Family', 'serviceCode', 'Location',
       'Location Type', 'Instance Type', 'Current Generation',
       'Instance Family', 'vCPU', 'Physical Processor', 'Clock Speed',
       'Memory', 'Storage', 'Network Performance', 'Processor Architecture',
       'Storage Media', 'Volume Type', 'Max Volume Size', 'Max IOPS/volume',
       'Max IOPS Burst Performance', 'Max throughput/volume', 'Provisioned',
       'Tenancy', 'EBS Optimized', 'Operating System', 'License Model',
       'Group', 'Group Description', 'Transfer Type', 'From Location',
       'From Location Type', 'To Location', 'To Location Type', 'usageType',
       'operation', 'CapacityStatus', 'Dedicated EBS Throughput', 'ECU',
       'Elastic Graphics Type', 'Enhanced Networking Supported', 'GPU',
       'GPU Memory', 'Instance', 'Instance Capacity - 10xlarge',
       'Instance Capacity - 12xlarge', 'Instance Capacity - 16xlarge',
       'Instance Capacity - 18xlarge', 'Instance Capacity - 24xlarge',
       'Instance Capacity - 2xlarge', 'Instance Capacity - 32xlarge',
       'Instance Capacity - 4xlarge', 'Instance Capacity - 8xlarge',
       'Instance Capacity - 9xlarge', 'Instance Capacity - large',
       'Instance Capacity - medium', 'Instance Capacity - metal',
       'Instance Capacity - xlarge', 'instanceSKU', 'Intel AVX Available',
       'Intel AVX2 Available', 'Intel Turbo Available',
       'Normalization Size Factor', 'Physical Cores', 'Pre Installed S/W',
       'Processor Features', 'Product Type', 'Resource Type', 'serviceName',
       'Volume API Name'],
      dtype='object')

In [9]:
#pruned df

In [10]:
pdf = df[['Instance Type', 'PricePerUnit','Location', 'Tenancy', 'Operating System', 'PurchaseOption', 
          'TermType', 'operation']]

In [11]:
# pdf = df[['Instance Type', 'PricePerUnit','Location', 'Tenancy', 'Operating System', 'PurchaseOption', 'TermType', 'operation', 'PriceDescription']]

In [12]:
pdf

,Instance Type,PricePerUnit,Location,Tenancy,Operating System,PurchaseOption,TermType,operation
0,m4.xlarge,0.1963,US East (Ohio),Dedicated,RHEL,No Upfront,Reserved,RunInstances:0010
1,t4g.medium,0.0167,US West (Oregon),Shared,Linux,No Upfront,Reserved,RunInstances
2,r5dn.metal,22.0310,AWS GovCloud (US-West),Dedicated,Windows,Partial Upfront,Reserved,RunInstances:0102
3,i3.xlarge,0.1950,Asia Pacific (Tokyo),Dedicated,Linux,No Upfront,Reserved,RunInstances
4,m4.large,6972.0000,US East (N. Virginia),Dedicated,Linux,Partial Upfront,Reserved,RunInstances:0004
...,...,...,...,...,...,...,...,...
1814576,m4.16xlarge,0.0000,Asia Pacific (Tokyo),Dedicated,SUSE,All Upfront,Reserved,RunInstances:000g
1814577,m5a.4xlarge,7.6340,Asia Pacific (Seoul),Dedicated,Windows,NaN,OnDemand,RunInstances:0102
1814578,m5d.24xlarge,15.4920,US East (N. Virginia),Shared,Linux,No Upfront,Reserved,RunInstances:0004
1814579,c5n.xlarge,9437.0000,Asia Pacific (Seoul),Shared,Windows,All Upfront,Reserved,RunInstances:0202
1814580,i3.metal,29.1580,Africa (Cape Town),Shared,Linux,No Upfront,Reserved,RunInstances:0100

In [13]:
sub1=pdf[(pdf['Location'] == 'US West (Oregon)') & (pdf["Tenancy"] == 'Shared') & (pdf['Operating System'] == 'Linux')]

In [14]:
sub1

,Instance Type,PricePerUnit,Location,Tenancy,Operating System,PurchaseOption,TermType,operation
1,t4g.medium,0.0167,US West (Oregon),Shared,Linux,No Upfront,Reserved,RunInstances
268,c5d.12xlarge,62325.0000,US West (Oregon),Shared,Linux,All Upfront,Reserved,RunInstances:0004
375,c5a.large,529.0000,US West (Oregon),Shared,Linux,Partial Upfront,Reserved,RunInstances:0200
395,m5n.24xlarge,344782.0000,US West (Oregon),Shared,Linux,All Upfront,Reserved,RunInstances:0100
398,r5dn.2xlarge,0.4480,US West (Oregon),Shared,Linux,No Upfront,Reserved,RunInstances:0200
...,...,...,...,...,...,...,...,...
1814367,m6g.4xlarge,0.2678,US West (Oregon),Shared,Linux,No Upfront,Reserved,RunInstances
1814439,m4.xlarge,0.2800,US West (Oregon),Shared,Linux,Partial Upfront,Reserved,RunInstances:0004
1814440,c5d.12xlarge,31284.0000,US West (Oregon),Shared,Linux,Partial Upfront,Reserved,RunInstances:0004
1814495,r5b.2xlarge,29810.0000,US West (Oregon),Shared,Linux,All Upfront,Reserved,RunInstances:0100
1814574,r5.8xlarge,2.5250,US West (Oregon),Shared,Linux,Partial Upfront,Reserved,RunInstances:0004

In [15]:
t3 = sub1[(sub1['Instance Type'] == 't3a.2xlarge')  & (sub1['TermType'] =='OnDemand') & 
          (sub1['operation'] =='RunInstances') & (sub1['PricePerUnit'] > 0)]

In [16]:
t3

,Instance Type,PricePerUnit,Location,Tenancy,Operating System,PurchaseOption,TermType,operation
552183,t3a.2xlarge,0.3008,US West (Oregon),Shared,Linux,NaN,OnDemand,RunInstances
678751,t3a.2xlarge,0.3008,US West (Oregon),Shared,Linux,NaN,OnDemand,RunInstances

In [17]:
t3u = t3.iloc[0]

In [18]:
t3u.PricePerUnit    * 365 * 24 / 12

219.58399999999997

In [19]:
weekend_savings = 48*4.5 * t3u.PricePerUnit 
weekend_savings

64.9728

In [20]:
annual_savings = weekend_savings * 12
annual_savings

779.6736000000001

In [21]:
df.loc[678751].values

array(['W6JYXGAFAS6XJ4RM', 'JRTCKXETXF',
       'W6JYXGAFAS6XJ4RM.JRTCKXETXF.6YS6EN2CT7', 'OnDemand',
       '$0.3008 per On Demand Linux t3a.2xlarge Instance Hour',
       '2020-12-01', 0.0, inf, 'Hrs', 0.3008, 'USD', nan, nan, nan, nan,
       'Compute Instance', 'AmazonEC2', 'US West (Oregon)', 'AWS Region',
       't3a.2xlarge', 'Yes', 'General purpose', 8.0, 'AMD EPYC 7571',
       '2.5 GHz', '32 GiB', 'EBS only', 'Up to 5 Gigabit', '64-bit', nan,
       nan, nan, nan, nan, nan, nan, 'Shared', nan, 'Linux',
       'No License required', nan, nan, nan, nan, nan, nan, nan,
       'USW2-BoxUsage:t3a.2xlarge', 'RunInstances', 'Used',
       'Up to 2780 Mbps', 'Variable', nan, 'Yes', nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       'No', 'No', 'No', 16.0, nan, nan, 'AVX; AVX2; AMD Turbo', nan, nan,
       'Amazon Elastic Compute Cloud', nan], dtype=object)

In [22]:
dir(df.loc[678751])

['CapacityStatus',
 'Currency',
 'ECU',
 'EffectiveDate',
 'EndingRange',
 'GPU',
 'Group',
 'Instance',
 'LeaseContractLength',
 'Location',
 'Memory',
 'OfferTermCode',
 'OfferingClass',
 'PriceDescription',
 'PricePerUnit',
 'Provisioned',
 'PurchaseOption',
 'RateCode',
 'RelatedTo',
 'SKU',
 'StartingRange',
 'Storage',
 'T',
 'Tenancy',
 'TermType',
 'Unit',
 '_AXIS_LEN',
 '_AXIS_NAMES',
 '_AXIS_NUMBERS',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_add_numeric_operations',
 '_add_series_or_dataframe_operations',
 '_agg_by_level',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_aggregate',
 '_aggregate_multiple_funcs',
 '_align_frame',
 '_align_series',
 '_binop',
 '_builtin_table',
 '_can_hold_na',
 '_check_inplace_setting',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_axes_from_arguments',
 '_construct_result',
 '_constructor',
 '_constructor_expanddim',
 '_constructor_sliced',
 '_convert',
 '_convert_dtypes',
 '_cython_table',
 '_data',
 '_deprecations',
 '_dir_additions',
 '_dir_deletions',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_find_valid_index',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cacher',
 '_get_cleaned_column_resolvers',
 '_get_cython_func',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values',
 '_get_values_tuple',
 '_get_with',
 '_gotitem',
 '_index',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_init_dict',
 '_init_mgr',
 '_internal_names',
 '_internal_names_set',
 '_is_builtin_func',
 '_is_cached',
 '_is_copy',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_iset_item',
 '_ix',
 '_ixs',
 '_map_values',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_needs_reindex_multi',
 '_obj_with_exclusions',
 '_protect_consolidate',
 '_reduce',
 '_reindex_axes',
 '_reindex_indexer',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_repr_data_resource_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_selected_obj',
 '_selection',
 '_selection_list',
 '_selection_name',
 '_set_as_cached',
 '_set_axis',
 '_set_axis_name',
 '_set_is_copy',
 '_set_item',
 '_set_labels',
 '_set_name',
 '_set_value',
 '_set_values',
 '_set_with',
 '_set_with_engine',
 '_slice',
 '_stat_axis',
 '_stat_axis_name',
 '_stat_axis_number',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_try_aggregate_string_function',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'append',
 'apply',
 'argmax',
 'argmin',
 'argsort',
 'array',
 'asfreq',
 'asof',
 'astype',
 'at',
 'at_time',
 'attrs',
 'autocorr',
 'axes',
 'backfill',
 'between',
 'between_time',
 'bfill',
 'bool',
 'clip',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'divmod',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtype',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'ewm',
 'expanding',
 'explode',
 'factorize',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'floordiv',
 'ge',
 'get',
 'groupby',
 'gt',
 'hasnans',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'instanceSKU',
 'interpolate',
 'is_monotonic',
 'is_monotonic_decreasing',
 'is_monotonic_increasing',
 'is_unique',
 'isin',
 'isna',
 'isnull',
 'item',
 'items',
 'iteritems',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'mad',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'memory_usage',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'name',
 'nbytes',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'operation',
 'pad',
 'pct_change',
 'pipe',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'radd',
 'rank',
 'ravel',
 'rdiv',
 'rdivmod',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'repeat',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'searchsorted',
 'sem',
 'serviceCode',
 'serviceName',
 'set_axis',
 'shape',
 'shift',
 'size',
 'skew',
 'slice_shift',
 'sort_index',
 'sort_values',
 'squeeze',
 'std',
 'str',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_frame',
 'to_hdf',
 'to_json',
 'to_latex',
 'to_list',
 'to_markdown',
 'to_numpy',
 'to_period',
 'to_pickle',
 'to_sql',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unique',
 'unstack',
 'update',
 'usageType',
 'vCPU',
 'value_counts',
 'values',
 'var',
 'view',
 'where',
 'xs']

In [23]:
#$0.3008 per On Demand Linux t3a.2xlarge Instan...

df.loc[1425139].values

array(['DDZ8GG3MUTUNYXC3', 'JRTCKXETXF',
       'DDZ8GG3MUTUNYXC3.JRTCKXETXF.6YS6EN2CT7', 'OnDemand',
       '$0.00 per Reservation Linux t3a.2xlarge Instance Hour',
       '2020-12-01', 0.0, inf, 'Hrs', 0.0, 'USD', nan, nan, nan, nan,
       'Compute Instance', 'AmazonEC2', 'US West (Oregon)', 'AWS Region',
       't3a.2xlarge', 'Yes', 'General purpose', 8.0, 'AMD EPYC 7571',
       '2.5 GHz', '32 GiB', 'EBS only', 'Up to 5 Gigabit', '64-bit', nan,
       nan, nan, nan, nan, nan, nan, 'Shared', nan, 'Linux',
       'No License required', nan, nan, nan, nan, nan, nan, nan,
       'USW2-Reservation:t3a.2xlarge', 'RunInstances',
       'AllocatedCapacityReservation', 'Up to 2780 Mbps', 'Variable', nan,
       'Yes', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, 'W6JYXGAFAS6XJ4RM', 'No', 'No', 'No',
       16.0, nan, nan, 'AVX; AVX2; AMD Turbo', nan, nan,
       'Amazon Elastic Compute Cloud', nan], dtype=object)

In [24]:
ddf = sub1[ (sub1['TermType'] =='OnDemand') & 
          (sub1['operation'] =='RunInstances') & (sub1['PricePerUnit'] > 0)]

In [25]:
ddf

,Instance Type,PricePerUnit,Location,Tenancy,Operating System,PurchaseOption,TermType,operation
4946,r6gd.metal,3.6864,US West (Oregon),Shared,Linux,NaN,OnDemand,RunInstances
14473,m5ad.24xlarge,4.9440,US West (Oregon),Shared,Linux,NaN,OnDemand,RunInstances
15909,r5d.16xlarge,4.6080,US West (Oregon),Shared,Linux,NaN,OnDemand,RunInstances
22851,r4.large,0.1330,US West (Oregon),Shared,Linux,NaN,OnDemand,RunInstances
25035,r4.16xlarge,4.2560,US West (Oregon),Shared,Linux,NaN,OnDemand,RunInstances
...,...,...,...,...,...,...,...,...
1798648,m5d.2xlarge,0.4520,US West (Oregon),Shared,Linux,NaN,OnDemand,RunInstances
1804897,c6gd.metal,2.4576,US West (Oregon),Shared,Linux,NaN,OnDemand,RunInstances
1807580,inf1.6xlarge,1.9040,US West (Oregon),Shared,Linux,NaN,OnDemand,RunInstances
1809718,r5dn.4xlarge,1.3360,US West (Oregon),Shared,Linux,NaN,OnDemand,RunInstances
1812744,g4ad.4xlarge,0.8670,US West (Oregon),Shared,Linux,NaN,OnDemand,RunInstances

In [36]:
for i,v in ddf.iterrows():
    i_type = v['Instance Type']
    if ('t3' in i_type):
        print(v['Instance Type'])
    if ('p2' in i_type):
        print(i_type)

t3a.xlarge
t3a.large
p2.xlarge
t3.2xlarge
t3a.small
t3a.medium
p2.8xlarge
t3.2xlarge
t3a.large
t3a.2xlarge
t3.xlarge
t3a.2xlarge
t3.medium
t3.large
p2.8xlarge
t3a.xlarge
t3a.small
t3.xlarge
t3a.nano
t3.nano
t3a.micro
t3.micro
t3.micro
p2.16xlarge
p2.16xlarge
t3.large
t3.nano
t3.small
t3a.micro
t3a.nano
t3.medium
t3.small
t3a.medium
p2.xlarge

In [38]:
import pickle
filename = 'price_prune.pickle'
outfile = open(filename,'wb')

pickle.dump(ddf, outfile)
outfile.close()